### ISSUE TITLE
[RFC] XML services

### ISSUE THREAD

**Issue by DonCallisto** [jakzal/BehatNoExtension#10]
I've noticed that services could be loaded only from `.yml` files but to me it should be possibile to give also `.xml` format.
Maybe we can let the user decide with this policy: default `.yml` (will not BC) otherwise specify `.xml` or we can try find both (but I would prefer a more explicit one).

What do you think?

**Comment by jakzal** [comment]
Personally, I thought that since Behat configuration only supports yml (from the end user's perspective, internally it uses php) there's no need for other formats. However, if others prefer xml (or php) I see no reason why we shouldn't do it. The implementation would be very simple as we'd only need to initialize appropriate loaders.

**Comment by DonCallisto** [comment]
Yes, behat supports only `yml` but that's not strictly adherent to behat concepts as it mixes behat and symfony concepts (like symfony container). 

So what you think about this? If it's good, would you act by parse `xml` files also, or you would expose some configuration in order to specify the format? 

Maybe first solution - in case - is more flexible

**Comment by jakzal** [comment]
@DonCallisto I wanted to keep it simple and only implemented `yml`. If anyone prefers to use other formats, I'll accept a PR. It's relatively easy to implement with the `DelegatingLoader`.

**Comment by DonCallisto** [comment]
Ok, so let's close it
